title: Replace State Altering Conditionals with State
initial_situation: The conditional expressions that control an object's state transitions are complex.
target_situation: Replace the conditionals with State classes that handle specific states and transitions between them.
difficulty: easy

fixes: [conditional-complexity]

pros:
    - "Reduces or removes state-changing conditional logic.\r"
    - "Simplifies complex state-changing logic.\r"
    - 'Provides a good bird''s-eye view of state-changing logic.'

cons:
    - 'Complicates a design when state transition logic is already easy to follow.'

examples:
    doctrine-entity:
        title: Doctrine Entity