title: Move Embellishment to Decorator
initial_situation: Code provides an embellishment to a class's core responsibility.
target_situation: Move the embellishment code to a Decorator.
difficulty: medium

fixes: [conditional-complexity]

pros:
    - "Simplifies a class by removing embellishments from it.\r"
    - "Effectively distinguishes a class's core reponsibility from its embellishments.\r"
    - 'Helps remove duplicated embellishment logic in several related classes.'

intro: ''

cons:
    - "Changes the object identity of a decorated object.\r"
    - "Can make code harder to understand an debug.\r"
    - 'Complicates a design when combinations of Decorators can adversely affect one another.'
