title: Create Template Method
initial_situation: Two methods in subclasses perform similar steps in the same order, yet steps are different.
target_situation: Generalize the methods by extracting their steps into methods with identical signatures, then pull up the generalized methods to create a Template Method.
difficulty: easy

fixes: [duplicated-code]
intro: ''